//
// modelOne (m1, "1") is a unidirectional event storm
// randomly generated by all the configured gateways
// Server selection is random as well
// Upon reception, server simply drops the event to the floor
// and goes on listening
//
// Framework services utilized by this model:
// - time, events and event comm,
// - multitasking, stats reporting, logging
//
package surge

import (
	"time"
)

// implements ModelInterface
type modelOne struct {
}

type gatewayOne struct {
	RunnerBase
}

type serverOne struct {
	RunnerBase
}

//
// init
//
func init() {
	d := NewStatsDescriptors("1")
	d.Register("event", StatsKindCount, StatsScopeServer)
	d.Register("rxbusy", StatsKindPercentage, StatsScopeServer)
	d.Register("txbytes", StatsKindByteCount, StatsScopeGateway)

	props := make(map[string]interface{}, 1)
	props["description"] = "unidirectional storm of random events"
	// props["GOMAXPROCS"] = 1
	RegisterModel("1", &modelOne{}, props)
}

//==================================================================
//
// gatewayOne methods
//
//==================================================================
//
// generate random event (storm) => random servers
//
func (r *gatewayOne) Run() {
	r.state = RstateRunning

	go func() {
		for r.state == RstateRunning {
			r.send()
			time.Sleep(time.Microsecond * 100)
		}
		r.closeTxChannels()
	}()
}

func (r *gatewayOne) send() {
	sr := r.selectRandomPeer(64) // hardcoded max load
	if sr != nil {
		at := clusterTripPlusRandom()
		r.Send(newTimedAnyEvent(r, at, sr), SmethodDontWait)
	}
}

//==================================================================
//
// serverOne methods
//
//==================================================================
func (r *serverOne) Run() {
	r.state = RstateRunning

	// event handling is a NOP in this model
	rxcallback := func(ev EventInterface) int {
		assert(r == ev.GetTarget())
		log(LogVV, "proc-ed", ev.String())
		return 0
	}

	go func() {
		for r.state == RstateRunning {
			r.receiveEnqueue()
			time.Sleep(time.Microsecond)
			r.processPendingEvents(rxcallback)
		}
	}()
}

//==================================================================
//
// ModelInterface methods
//
//==================================================================
func (m *modelOne) NewGateway(i int) RunnerInterface {
	gwy := &gatewayOne{RunnerBase{id: i, strtype: "GWY"}}
	gwy.init(config.numServers)
	return gwy
}

func (m *modelOne) NewServer(i int) RunnerInterface {
	srv := &serverOne{RunnerBase: RunnerBase{id: i, strtype: "SRV"}}
	srv.init(config.numGateways)
	return srv
}

func (m *modelOne) Configure() {
	config.timeClusterTrip = time.Microsecond * 2
}
