//
// ModelOne (m1, "one") is a unidirectional event storm
// randomly generated by all the configured gateways
// Server selection is random as well
// Upon reception, server simply drops the event to the floor
// and goes on listening
//
// Framework services utilized by this model:
// - time, events and event comm,
// - multitasking, stats reporting, logging
//
package surge

import (
	"math/rand"
	"time"
)

// implements ModelInterface
type ModelOne struct {
}

type GatewayOne struct {
	RunnerBase
}

type ServerOne struct {
	RunnerBase
}

//
// init
//
func init() {
	d := NewStatsDescriptors("one")
	d.Register("event", StatsKindCount, StatsScopeServer)

	props := make(map[string]interface{}, 1)
	props["description"] = "unidirectional storm of random events"
	RegisterModel("one", &ModelOne{}, props)
}

//==================================================================
//
// GatewayOne methods
//
//==================================================================
//
// generate random event (storm) => random servers
//
func (r *GatewayOne) Run() {
	r.state = RstateRunning

	go func() {
		for r.state == RstateRunning {
			r.send()
			time.Sleep(time.Microsecond * 100)
		}
		r.closeTxChannels()
	}()
}

func (r *GatewayOne) send() {
	trip := config.timePhysTrip
	sr := r.selectRandomPeer(64) // hardcoded max load
	if sr != nil {
		txch, _ := r.getChannels(sr)
		at := rand.Int63n(int64(trip)) + int64(trip)
		txch <- newTimedUcastEvent(r, time.Duration(at), sr)
	}
}

//==================================================================
//
// ServerOne methods
//
//==================================================================
func (r *ServerOne) Run() {
	r.state = RstateRunning

	// event handling is a NOP in this model
	rxcallback := func(ev EventInterface) bool {
		assert(r == ev.GetTarget())
		log(LOG_VV, "proc-ed", ev.String())
		return true
	}

	go func() {
		for r.state == RstateRunning {
			r.receiveAndHandle(rxcallback)

			time.Sleep(time.Microsecond)
			r.processPendingEvents(rxcallback)
		}
	}()
}

//==================================================================
//
// ModelInterface methods
//
//==================================================================
func (m *ModelOne) NewGateway(i int) RunnerInterface {
	gwy := &GatewayOne{RunnerBase{id: i, strtype: "GWY"}}
	gwy.init(config.numServers)
	return gwy
}

func (m *ModelOne) NewServer(i int) RunnerInterface {
	srv := &ServerOne{RunnerBase: RunnerBase{id: i, strtype: "SRV"}}
	srv.init(config.numGateways)
	return srv
}

func (m *ModelOne) NewDisk(i int) RunnerInterface { return nil }
